remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-include-cache

minimal_mistakes_skin: "dark"
locale: "en-US"
title: "todash space"
subtitle: "the void that exists between worlds"
name: "Lester L"
description: "just a placeholder for my email domain"
url: "https://todash.space"
repository: "lesterlxy/todash.space"
masthead_title: "todash space"
author:
  name     : "Lester L"
  avatar   : "/assets/images/avatar.png"
  bio      : "placeholder"
  location : "Singapore"
